# Generated by Django 4.2 on 2023-04-21 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
